apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tf-worker
spec:
  minReplicas: 1
  maxReplicas: 450
  metrics:
  - external:
      metricName: pubsub.googleapis.com|subscription|num_undelivered_messages
      metricSelector:
        matchLabels:
          resource.labels.subscription_id: video-experiments-sub
      targetAverageValue: "6"
    type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tf-worker
